// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NikeStore.Models;

#nullable disable

namespace NikeStoreCore.Migrations
{
    [DbContext(typeof(NikeContext))]
    [Migration("20240204100147_SeedDatabase")]
    partial class SeedDatabase
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.26")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("NikeStore.Entities.Order", b =>
                {
                    b.Property<int>("OrderID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderID"), 1L, 1);

                    b.Property<string>("Addres")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Client")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.HasKey("OrderID");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("NikeStore.Entities.OrderItems", b =>
                {
                    b.Property<int>("Order_Id")
                        .HasColumnType("int")
                        .HasColumnOrder(1);

                    b.Property<int>("Shoe_Id")
                        .HasColumnType("int")
                        .HasColumnOrder(2);

                    b.HasKey("Order_Id", "Shoe_Id");

                    b.ToTable("OrderItems");
                });

            modelBuilder.Entity("NikeStore.Entities.Shoe", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Shoes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "AirForce1Blue",
                            Picture = "https://picsum.photos/200/300?random=1",
                            Price = 199f,
                            Size = "41,42,43,44"
                        },
                        new
                        {
                            Id = 2,
                            Name = "AirJordan1RetroLow4",
                            Picture = "https://picsum.photos/200/300?random=2",
                            Price = 240f,
                            Size = "41,42,43,44"
                        },
                        new
                        {
                            Id = 3,
                            Name = "AirJordan2Wing",
                            Picture = "https://picsum.photos/200/300?random=3",
                            Price = 180f,
                            Size = "41,42,43,44"
                        },
                        new
                        {
                            Id = 4,
                            Name = "AirJordan4From",
                            Picture = "https://picsum.photos/200/300?random=4",
                            Price = 270f,
                            Size = "38"
                        },
                        new
                        {
                            Id = 5,
                            Name = "AirJOrdan4Knicks",
                            Picture = "https://picsum.photos/200/300?random=5",
                            Price = 140f,
                            Size = "41,42,43,44"
                        },
                        new
                        {
                            Id = 6,
                            Name = "AirJordan4Retro",
                            Picture = "https://picsum.photos/200/300?random=6",
                            Price = 230f,
                            Size = "38"
                        },
                        new
                        {
                            Id = 7,
                            Name = "AirJordan5",
                            Picture = "https://picsum.photos/200/300?random=7",
                            Price = 320f,
                            Size = "45,46,47"
                        });
                });

            modelBuilder.Entity("NikeStore.Entities.ShoeTag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Shoe_Id")
                        .HasColumnType("int");

                    b.Property<int>("Tag_Id")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShoeTags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Shoe_Id = 1,
                            Tag_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            Shoe_Id = 2,
                            Tag_Id = 2
                        },
                        new
                        {
                            Id = 3,
                            Shoe_Id = 3,
                            Tag_Id = 3
                        },
                        new
                        {
                            Id = 4,
                            Shoe_Id = 4,
                            Tag_Id = 4
                        },
                        new
                        {
                            Id = 5,
                            Shoe_Id = 5,
                            Tag_Id = 5
                        },
                        new
                        {
                            Id = 6,
                            Shoe_Id = 6,
                            Tag_Id = 6
                        },
                        new
                        {
                            Id = 7,
                            Shoe_Id = 7,
                            Tag_Id = 7
                        });
                });

            modelBuilder.Entity("NikeStore.Entities.Tag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Tags");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Winter"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Summer"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Men"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Autumn"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Spring"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Women"
                        },
                        new
                        {
                            Id = 7,
                            Name = "New"
                        });
                });

            modelBuilder.Entity("NikeStore.Entities.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "nikihouse",
                            Email = "nikiv@gmail.com",
                            FirstName = "nikiv",
                            IsAdmin = false,
                            LastName = "nikipass",
                            Password = "nikipass",
                            PhoneNumber = "0896543210",
                            Username = "nikiv"
                        },
                        new
                        {
                            Id = 2,
                            Address = "Memo",
                            Email = "semo@abv.bg",
                            FirstName = "semo",
                            IsAdmin = true,
                            LastName = "memo",
                            Password = "memo",
                            PhoneNumber = "0896543210",
                            Username = "semo"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
